services:
  auth-db:
    image: mysql:8
    container_name: auth-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mdx20020327@
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
      - ./auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pmdx20020327@"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  listing-db:
    image: mysql:8
    container_name: listing-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: KivinduM123!
      MYSQL_DATABASE: room_booking
    ports:
      - "3308:3306"
    volumes:
      - listing_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pKivinduM123!"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "5001:5001"
    depends_on:
      auth-db:
        condition: service_healthy
    restart: unless-stopped

  listing-service:
    build:
      context: ./listing-service
      dockerfile: Dockerfile
    container_name: listing-service
    env_file:
      - ./listing-service/.env
    ports:
      - "5000:5000"
    depends_on:
      listing-db:
        condition: service_healthy
      auth-service:
        condition: service_started
    restart: unless-stopped

volumes:
  auth_db_data:
  listing_db_data:
